"""empty message

Revision ID: 211a049d7415
Revises: a15e4665fda8
Create Date: 2017-11-18 15:43:09.874854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211a049d7415'
down_revision = 'a15e4665fda8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('picture_path', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'picture_path')
    # ### end Alembic commands ###
