"""empty message

Revision ID: a15e4665fda8
Revises: aa23b9b44d9c
Create Date: 2017-11-17 18:58:28.834779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a15e4665fda8'
down_revision = 'aa23b9b44d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_requestors', sa.Column('price', sa.Float(precision=10), nullable=True))
    op.add_column('jobs', sa.Column('price', sa.Float(precision=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'price')
    op.drop_column('job_requestors', 'price')
    # ### end Alembic commands ###
